name: CI

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Building...
      shell: bash
      run: ./build.sh release
    - name: Uploading binary artifact...
      uses: actions/upload-artifact@v2
      with:
        name: rive_sokol-win32.exe
        path: build/bin/release/rive_sokol.exe
    - name: Uploading library artifact...
      uses: actions/upload-artifact@v2
      with:
        name: rive-private-api-win32
        path: |
          build/bin/release/librivesokol.a
          src/rive/rive_render_api.h
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Building...
      run: ./build.sh release
    - name: Uploading binary artifact...
      uses: actions/upload-artifact@v2
      with:
        name: rive_sokol-osx
        path: build/bin/release/rive_sokol
    - name: Uploading library artifact...
      uses: actions/upload-artifact@v2
      with:
        name: rive-private-api-osx
        path: |
          build/bin/release/librivesokol.a
          src/rive/rive_render_api.h
